
package cl.contraloria.sicogen.ws.valida.informe;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ValidacionSOAP11BindingQSService", targetNamespace = "http://www.cgr.cl/osb/informes/ic/v2/sigfe/validacion", wsdlLocation = "http://172.30.21.57:7003/informes/sp/ic/v2/sigfe/validacion?wsdl")
public class ValidacionSOAP11BindingQSService
    extends Service
{

    private final static URL VALIDACIONSOAP11BINDINGQSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(ValidacionSOAP11BindingQSService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = ValidacionSOAP11BindingQSService.class.getResource(".");
            url = new URL(baseUrl, "http://172.30.21.57:7003/informes/sp/ic/v2/sigfe/validacion?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://172.30.21.57:7003/informes/sp/ic/v2/sigfe/validacion?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        VALIDACIONSOAP11BINDINGQSSERVICE_WSDL_LOCATION = url;
    }

    public ValidacionSOAP11BindingQSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidacionSOAP11BindingQSService() {
        super(VALIDACIONSOAP11BINDINGQSSERVICE_WSDL_LOCATION, new QName("http://www.cgr.cl/osb/informes/ic/v2/sigfe/validacion", "ValidacionSOAP11BindingQSService"));
    }

    /**
     * 
     * @return
     *     returns ValidacionPortType
     */
    @WebEndpoint(name = "ValidacionSOAP11BindingQSPort")
    public ValidacionPortType getValidacionSOAP11BindingQSPort() {
        return super.getPort(new QName("http://www.cgr.cl/osb/informes/ic/v2/sigfe/validacion", "ValidacionSOAP11BindingQSPort"), ValidacionPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidacionPortType
     */
    @WebEndpoint(name = "ValidacionSOAP11BindingQSPort")
    public ValidacionPortType getValidacionSOAP11BindingQSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.cgr.cl/osb/informes/ic/v2/sigfe/validacion", "ValidacionSOAP11BindingQSPort"), ValidacionPortType.class, features);
    }

}
