
package cl.contraloria.sicogen.ws.valida.informe;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ValidacionPortType", targetNamespace = "http://www.cgr.cl/osb/informes/ic/v2/sigfe/validacion")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidacionPortType {


    /**
     * 
     * @param request
     */
    @WebMethod(action = "http://www.cgr.cl/osb/informes/ic/v2/sigfe/validaInforme")
    @Oneway
    public void validaInforme(
        @WebParam(name = "validaInformeRequest", targetNamespace = "http://www.contraloria.cl/xml/esquemas", partName = "request")
                ValidaInformeRequestType request);

}
